app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from . import db
from .models import User, Paciente, Consulta, Procedimento, Medicamento, Receita, ReceitaMedicamento
from .forms import LoginForm, CadastroPacienteForm, AgendamentoConsultaForm, RegistrationForm, ReceitaForm, EditarPacienteForm
from datetime import datetime

bp = Blueprint('main', __name__)

@bp.route('/')
@login_required
def index():
    return render_template('admin.html')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.index'))
        else:
            flash('Invalid username or password.')
    return render_template('login.html', form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

@bp.route('/cadastro_paciente', methods=['GET', 'POST'])
@login_required
def cadastro_paciente():
    form = CadastroPacienteForm()
    if form.validate_on_submit():
        try:
            paciente = Paciente(
                nome=form.nome.data,
                cpf_cnpj=form.cpf_cnpj.data,
                cep=form.cep.data,
                endereco=form.endereco.data,
                numero_residencia=form.numero_residencia.data,
                cidade=form.cidade.data,
                estado=form.estado.data,
                telefone=form.telefone.data,
                email=form.email.data,
                data_nascimento=form.data_nascimento.data,
                genero=form.genero.data,
                convenio=form.convenio.data,
                numero_convenio=form.numero_convenio.data
            )
            db.session.add(paciente)
            db.session.commit()
            idade = form.calcular_idade()
            flash(f'Paciente cadastrado com sucesso! Idade: {idade} anos')
            return redirect(url_for('main.index'))
        except Exception as e:
            flash(f'Erro ao cadastrar paciente: {e}')
            db.session.rollback()
    return render_template('cadastro_paciente.html', form=form)

@bp.route('/agendar_consulta', methods=['GET', 'POST'])
@login_required
def agendar_consulta():
    form = AgendamentoConsultaForm()
    if form.validate_on_submit():
        try:
            print("Formulário validado com sucesso")
            consulta = Consulta(
                paciente_id=form.paciente_id.data,
                especialidade=form.especialidade.data,
                data=form.data.data,
                hora=form.hora.data,
                procedimento_id=form.procedimento_id.data,
                status='agendado'
            )
            db.session.add(consulta)
            db.session.commit()
            print("Consulta agendada com sucesso")
            flash('Consulta agendada com sucesso!')
            return redirect(url_for('main.index'))
        except Exception as e:
            print(f"Erro ao agendar consulta: {e}")
            flash(f'Erro ao agendar consulta: {e}')
            db.session.rollback()
    else:
        print("Formulário não validado")
        # Exibir dados do formulário e erros de validação
        print("Dados do formulário:")
        print(f"Paciente ID: {form.paciente_id.data}")
        print(f"Especialidade: {form.especialidade.data}")
        print(f"Data: {form.data.data}")
        print(f"Hora: {form.hora.data}")
        print(f"Procedimento ID: {form.procedimento_id.data}")

        print("Erros de validação:")
        for field, errors in form.errors.items():
            for error in errors:
                print(f"Erro no campo {field}: {error}")

    return render_template('agendamento_consulta.html', form=form)

@bp.route('/consultas', methods=['GET'])
@login_required
def get_consultas():
    consultas = Consulta.query.filter(Consulta.status == 'agendado').all()
    eventos = []
    for consulta in consultas:
        eventos.append({
            'title': f"{consulta.especialidade} - {consulta.procedimento.nome}",
            'start': f"{consulta.data}T{consulta.hora}",
            'status': consulta.status
        })
    return jsonify(eventos)

@bp.route('/consultas_dia', methods=['GET'])
@login_required
def consultas_dia():
    date_str = request.args.get('date')
    date = datetime.strptime(date_str, '%Y-%m-%d').date()
    consultas = Consulta.query.filter_by(data=date).all()
    return render_template('consultas_dia.html', consultas=consultas, date=date)

@bp.route('/consulta/<int:id>/gerar_receita', methods=['GET', 'POST'])
@login_required
def gerar_receita(id):
    consulta = Consulta.query.get_or_404(id)
    form = ReceitaForm()
    
    if form.validate_on_submit():
        try:
            receita = Receita(
                consulta_id=consulta.id,
                instrucoes=form.instrucoes.data
            )
            db.session.add(receita)
            db.session.commit()
            
            for medicamento_entry in form.medicamentos.entries:
                medicamento_nome = medicamento_entry.medicamento_id.data
                quantidade = medicamento_entry.quantidade.data
                medicamento = Medicamento.query.filter_by(nome=medicamento_nome).first()
                if not medicamento:
                    flash(f'Medicamento {medicamento_nome} não encontrado')
                    continue
                receita_medicamento = ReceitaMedicamento(
                    receita_id=receita.id,
                    medicamento_id=medicamento.id,
                    quantidade=quantidade
                )
                db.session.add(receita_medicamento)
            db.session.commit()
            
            flash('Receita gerada com sucesso!')
            return redirect(url_for('main.gerar_receita', id=consulta.id))  # Redireciona para a mesma página
        except Exception as e:
            db.session.rollback()
            flash(f'Erro ao gerar receita: {e}')
    else:
        # Exibir dados do formulário e erros de validação
        print("Formulário não validado")
        print("Dados do formulário:")
        print(f"Instruções: {form.instrucoes.data}")
        for field in form.medicamentos.entries:
            print(f"Medicamento ID: {field.medicamento_id.data}, Quantidade: {field.quantidade.data}")

        print("Erros de validação:")
        for field, errors in form.errors.items():
            for error in errors:
                print(f"Erro no campo {field}: {error}")

    return render_template('gerar_receita.html', form=form, consulta=consulta)

@bp.route('/receita/<int:id>/imprimir', methods=['GET'])
@login_required
def imprimir_receita(id):
    receita = Receita.query.get_or_404(id)
    return render_template('imprimir_receita.html', receita=receita)

@bp.route('/pesquisar_paciente', methods=['GET'])
@login_required
def pesquisar_paciente():
    query = request.args.get('query')
    pacientes = Paciente.query.filter(Paciente.nome.like(f'%{query}%')).all()
    return jsonify([{'id': pac.id, 'nome': pac.nome} for pac in pacientes])

@bp.route('/pesquisar_procedimento', methods=['GET'])
@login_required
def pesquisar_procedimento():
    query = request.args.get('query')
    procedimentos = Procedimento.query.filter(Procedimento.nome.ilike(f'%{query}%')).all()
    results = [{'id': proc.id, 'nome': proc.nome} for proc in procedimentos]
    return jsonify(results)

@bp.route('/consulta/<int:id>/atualizar_status', methods=['POST'])
@login_required
def atualizar_status_consulta(id):
    consulta = Consulta.query.get_or_404(id)
    status = request.form.get('status')
    if status:
        consulta.status = status
        db.session.commit()
        flash('Status da consulta atualizado com sucesso!')
    else:
        flash('Nenhum status fornecido.')
    return redirect(url_for('main.consultas_dia', date=consulta.data.strftime('%Y-%m-%d')))

@bp.route('/pesquisar_medicamento', methods=['GET'])
@login_required
def pesquisar_medicamento():
    query = request.args.get('query')
    medicamentos = Medicamento.query.filter(Medicamento.nome.like(f'%{query}%')).all()
    return jsonify([{'id': med.id, 'nome': med.nome} for med in medicamentos])

@bp.route('/buscar_paciente', methods=['GET', 'POST'])
@login_required
def buscar_paciente():
    if request.method == 'POST':
        query = request.form.get('query')
        pacientes = Paciente.query.filter(Paciente.nome.like(f'%{query}%')).all()
        return render_template('buscar_paciente.html', pacientes=pacientes)
    return render_template('buscar_paciente.html')

@bp.route('/paciente/<int:id>', methods=['GET'])
@login_required
def visualizar_paciente(id):
    paciente = Paciente.query.get_or_404(id)
    consultas = Consulta.query.filter_by(paciente_id=id).all()
    return render_template('visualizar_paciente.html', paciente=paciente, consultas=consultas, datetime=datetime)


@bp.route('/pacientes')
@login_required
def listar_pacientes():
    pacientes = Paciente.query.all()
    return render_template('listar_pacientes.html', pacientes=pacientes)

@bp.route('/paciente/<int:id>/editar', methods=['GET', 'POST'])

app/templates/admin.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administração</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/locale/pt-br.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url('{{ url_for('static', filename='images/background.png') }}') no-repeat center center fixed;
            background-size: cover;
        }
        #wrapper {
            display: flex;
            align-items: stretch;
        }
        #sidebar-wrapper {
            min-height: 100vh;
            width: 250px;
            background-color: rgba(248, 249, 250, 0.8);
            flex-shrink: 0;
            transition: margin 0.3s;
        }
        #page-content-wrapper {
            flex: 1;
            transition: margin 0.3s;
        }
        .list-group-item {
            padding: 20px;
            background: rgba(255, 255, 255, 0.8);
        }
        #wrapper.toggled #sidebar-wrapper {
            margin-left: 0;
        }
        #wrapper.toggled #page-content-wrapper {
            margin-left: 250px;
        }
        .fullcalendar-container {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 10px;
            padding: 15px;
        }
        #calendar {
            max-width: 900px;
            margin: 40px auto;
            background: rgba(255, 255, 255, 0.8);
            border-radius: 10px;
            padding: 15px;
        }
    </style>
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading"></div>
            <div class="list-group list-group-flush">
                <a href="{{ url_for('main.cadastro_paciente') }}" class="list-group-item list-group-item-action">Cadastro de Pacientes</a>
                <a href="{{ url_for('main.listar_pacientes') }}" class="list-group-item list-group-item-action">Lista de Pacientes</a>
                <a href="{{ url_for('main.agendar_consulta') }}" class="list-group-item list-group-item-action">Agendamento</a>
                <a href="{{ url_for('main.buscar_paciente') }}" class="list-group-item list-group-item-action">Prontuário</a>
                <a href="{{ url_for('main.logout') }}" class="list-group-item list-group-item-action">Logout</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">
                    <i class="fas fa-bars"></i>
                </button>
            </nav>
            <div class="container-fluid fullcalendar-container">
                <h1 class="mt-4">Consultas Agendadas</h1>
                <div id="calendar"></div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $(document).ready(function() {
            $('#calendar').fullCalendar({
                locale: 'pt-br', // Definindo o idioma do calendário
                events: '/consultas',
                dayMaxEvents: 4, // Limita o número máximo de eventos visíveis por dia
                dayClick: function(date, jsEvent, view) {
                    window.location.href = '/consultas_dia?date=' + date.format();
                },
                eventRender: function(event, element) {
                    // Customize the event color based on the status
                    if (event.status === 'agendado') {
                        element.css('background-color', '#007bff'); // Azul
                    } else if (event.status === 'em_andamento') {
                        element.css('background-color', '#ffc107'); // Amarelo
                    } else if (event.status === 'finalizado') {
                        element.css('background-color', '#28a745'); // Verde
                    }
                }
            });
        });
    </script>
</body>
</html>

app/templates/agendamento_consulta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendamento de Consulta</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url('{{ url_for('static', filename='images/background.png') }}') no-repeat center center fixed;
            background-size: cover;
        }
        .container {
            margin-top: 50px;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .form-group {
            margin-bottom: 1.5rem;
        }
        .form-control {
            border-radius: 5px;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }
        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #004085;
        }
        .input-group-append .btn {
            border-radius: 0 5px 5px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center my-4">Agendamento de Consulta</h2>
        <form method="POST" action="{{ url_for('main.agendar_consulta') }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.paciente_id(class="form-control d-none", id="paciente_id") }}
                <label for="paciente">Paciente</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="paciente" readonly>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#pacienteModal">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.especialidade.label(class="form-control-label") }}
                {{ form.especialidade(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.data.label(class="form-control-label") }}
                {{ form.data(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.hora.label(class="form-control-label") }}
                {{ form.hora(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.procedimento_id(class="form-control d-none", id="procedimento_id") }}
                <label for="procedimento">Procedimento</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="procedimento" readonly>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#procedimentoModal">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary btn-block") }}
            </div>
        </form>
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary btn-block mt-3">Voltar</a>
    </div>

    <!-- Modal de Pacientes -->
    <div class="modal fade" id="pacienteModal" tabindex="-1" role="dialog" aria-labelledby="pacienteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="pacienteModalLabel">Pesquisar Paciente</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" id="pesquisa_paciente" class="form-control" placeholder="Nome do Paciente">
                    </div>
                    <button type="button" class="btn btn-primary" id="buscarPaciente">Buscar</button>
                    <ul id="resultadoPesquisaPaciente" class="list-group mt-3"></ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal de Procedimentos -->
    <div class="modal fade" id="procedimentoModal" tabindex="-1" role="dialog" aria-labelledby="procedimentoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="procedimentoModalLabel">Pesquisar Procedimento</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" id="pesquisa_procedimento" class="form-control" placeholder="Nome do Procedimento">
                    </div>
                    <button type="button" class="btn btn-primary" id="buscarProcedimento">Buscar</button>
                    <ul id="resultadoPesquisaProcedimento" class="list-group mt-3"></ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            // Buscar paciente
            $('#buscarPaciente').click(function() {
                const query = $('#pesquisa_paciente').val();
                $.ajax({
                    url: "{{ url_for('main.pesquisar_paciente') }}",
                    method: "GET",
                    data: { query: query },
                    success: function(data) {
                        $('#resultadoPesquisaPaciente').empty();
                        data.forEach(function(paciente) {
                            $('#resultadoPesquisaPaciente').append(
                                `<li class="list-group-item" data-id="${paciente.id}" data-nome="${paciente.nome}">
                                    ${paciente.nome}
                                </li>`
                            );
                        });
                    }
                });
            });

            // Selecionar paciente
            $(document).on('click', '#resultadoPesquisaPaciente li', function() {
                const pacienteId = $(this).data('id');
                const pacienteNome = $(this).data('nome');
                $('#paciente').val(pacienteNome);
                $('#paciente_id').val(pacienteId);  // Definindo o ID do paciente no campo oculto
                $('#pacienteModal').modal('hide');
            });

            // Buscar procedimento
            $('#buscarProcedimento').click(function() {
                const query = $('#pesquisa_procedimento').val();
                $.ajax({
                    url: "{{ url_for('main.pesquisar_procedimento') }}",
                    method: "GET",
                    data: { query: query },
                    success: function(data) {
                        $('#resultadoPesquisaProcedimento').empty();
                        data.forEach(function(procedimento) {
                            $('#resultadoPesquisaProcedimento').append(
                                `<li class="list-group-item" data-id="${procedimento.id}" data-nome="${procedimento.nome}">
                                    ${procedimento.nome}
                                </li>`
                            );
                        });
                    }
                });
            });

            // Selecionar procedimento
            $(document).on('click', '#resultadoPesquisaProcedimento li', function() {
                const procedimentoId = $(this).data('id');
                const procedimentoNome = $(this).data('nome');
                $('#procedimento').val(procedimentoNome);
                $('#procedimento_id').val(procedimentoId);  // Definindo o ID do procedimento no campo oculto
                $('#procedimentoModal').modal('hide');
            });
        });
    </script>
</body>
</html>

app/templates/gerar_receita.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerar Receita</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url('{{ url_for('static', filename='images/background.png') }}') no-repeat center center fixed;
            background-size: cover;
        }
        .container {
            margin-top: 50px;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .medicamento-item {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        .medicamento-item input {
            margin-right: 10px;
        }
        .medicamento-item button {
            margin-left: 10px;
        }
        .autocomplete-suggestions {
            border: 1px solid #ccc;
            background: #fff;
            overflow: auto;
            position: absolute;
            z-index: 9999;
        }
        .autocomplete-suggestion {
            padding: 10px;
            cursor: pointer;
        }
        .autocomplete-suggestion:hover {
            background: #eee;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center my-4">Gerar Receita para Consulta - {{ consulta.id }}</h2>
        <div class="mb-4">
            <p><strong>Paciente:</strong> {{ consulta.paciente.nome }}</p>
            <p><strong>Procedimento:</strong> {{ consulta.procedimento.nome }}</p>
        </div>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="instrucoes">Instruções:</label>
                {{ form.instrucoes(class_='form-control') }}
            </div>
            <div class="form-group">
                <label for="medicamentos">Medicamentos:</label>
                <div id="medicamentos-container">
                    {% for field in form.medicamentos %}
                    <div class="medicamento-item">
                        {{ field.csrf_token }}
                        <div class="input-group">
                            {{ field.medicamento_id(class_='form-control medicamento', placeholder='Medicamento') }}
                        </div>
                        {{ field.quantidade(class_='form-control', placeholder='Quantidade', style='width: 100px;') }}
                        <button type="button" class="btn btn-danger" onclick="removeMedicamento(this)"><i class="fas fa-trash"></i></button>
                    </div>
                    {% endfor %}
                </div>
                <button type="button" class="btn btn-success" onclick="addMedicamento()"><i class="fas fa-plus"></i> Adicionar Medicamento</button>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Gerar Receita</button>
            <a href="{{ url_for('main.consultas_dia', date=consulta.data.strftime('%Y-%m-%d')) }}" class="btn btn-secondary btn-block mt-3">Voltar</a>
            {% if consulta.receitas %}
            <a href="{{ url_for('main.imprimir_receita', id=consulta.receitas[-1].id) }}" class="btn btn-success btn-block mt-3" target="_blank">Imprimir Receita</a>
            {% endif %}
        </form>
    </div>

    <script>
        let medicamentoCount = {{ form.medicamentos|length }};
        const csrfToken = "{{ form.csrf_token._value() }}"; // Obtém o token CSRF do formulário

        function addMedicamento() {
            medicamentoCount++;
            const container = document.getElementById('medicamentos-container');
            const newMedicamentoHtml = `
                <div class="medicamento-item">
                    <input type="hidden" name="medicamentos-${medicamentoCount}-csrf_token" value="${csrfToken}">
                    <div class="input-group">
                        <input type="text" name="medicamentos-${medicamentoCount}-medicamento_id" id="medicamentos-${medicamentoCount}-medicamento_id" class="form-control medicamento" placeholder="Medicamento">
                    </div>
                    <input type="text" name="medicamentos-${medicamentoCount}-quantidade" id="medicamentos-${medicamentoCount}-quantidade" class="form-control" placeholder="Quantidade" style="width: 100px;">
                    <button type="button" class="btn btn-danger" onclick="removeMedicamento(this)"><i class="fas fa-trash"></i></button>
                </div>`;
            container.insertAdjacentHTML('beforeend', newMedicamentoHtml);
            bindAutoComplete(`#medicamentos-${medicamentoCount}-medicamento_id`);
        }

        function removeMedicamento(button) {
            button.parentElement.remove();
        }

        function bindAutoComplete(selector) {
            $(selector).on('input', function() {
                const query = $(this).val();
                const target = $(this);
                if (query.length > 2) { // Fetch suggestions for queries longer than 2 characters
                    $.ajax({
                        url: "{{ url_for('main.pesquisar_medicamento') }}",
                        method: "GET",
                        data: { query: query },
                        success: function(data) {
                            let suggestions = data.map(item => `<div class="autocomplete-suggestion" data-id="${item.id}" data-nome="${item.nome}">${item.nome}</div>`).join('');
                            let suggestionsContainer = $(`<div class="autocomplete-suggestions">${suggestions}</div>`);
                            target.next('.autocomplete-suggestions').remove(); // Remove previous suggestions
                            target.after(suggestionsContainer);
                            $('.autocomplete-suggestion').on('click', function() {
                                target.val($(this).data('nome'));
                                target.next('.autocomplete-suggestions').remove();
                            });
                        }
                    });
                }
            });
        }

        // Bind autocomplete to initial medicamento fields
        $('.medicamento').each(function() {
            bindAutoComplete(`#${$(this).attr('id')}`);
        });
    </script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Projeto Flask</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="content-container">
        <h1>Bem-vindo ao meu projeto Flask!</h1>
        <a href="{{ url_for('main.logout') }}" class="btn btn-primary">Logout</a>
    </div>
</body>
</html>